{{- if not .Values.syncConfigSidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratelimit.fullname" . }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
data:
  config.yaml: |
    domain: example-1
    descriptors:
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 30
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratelimit.fullname" . }}-env
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- if eq .Values.env.USE_STATSD "true" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratelimit.fullname" . }}-statsd
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
data:
  conf.yaml: |
    mappings: # Requires statsd exporter >= v0.6.0 since it uses the "drop" action.
      - match:
          "ratelimit.service.rate_limit.*.*.near_limit"
        name: "ratelimit_service_rate_limit_near_limit"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
      - match:
          "ratelimit.service.rate_limit.*.*.over_limit"
        name: "ratelimit_service_rate_limit_over_limit"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
      - match:
          "ratelimit.service.rate_limit.*.*.total_hits"
        name: "ratelimit_service_rate_limit_total_hits"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
    
      - match:
          "ratelimit.service.rate_limit.*.*.*.near_limit"
        name: "ratelimit_service_rate_limit_near_limit"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
          key2: "$3"
      - match:
          "ratelimit.service.rate_limit.*.*.*.over_limit"
        name: "ratelimit_service_rate_limit_over_limit"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
          key2: "$3"
      - match:
          "ratelimit.service.rate_limit.*.*.*.total_hits"
        name: "ratelimit_service_rate_limit_total_hits"
        timer_type: "histogram"
        labels:
          domain: "$1"
          key1: "$2"
          key2: "$3"
    
      - match: "ratelimit.service.call.should_rate_limit.*"
        name: "ratelimit_service_should_rate_limit_error"
        match_metric_type: counter
        labels:
          err_type: "$1"
    
      - match: "ratelimit.service.config_load_success"
        name: "ratelimit_service_config_load_success"
        match_metric_type: counter
      - match: "ratelimit.service.config_load_error"
        name: "ratelimit_service_config_load_error"
        match_metric_type: counter
      - match: "ratelimit.service.config_load_error"
        name: "ratelimit_service_config_load_error"
        match_metric_type: counter
      - match: "."
        match_type: "regex"
        action: "drop"
        name: "dropped"
{{- end }}
