{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ratelimit.serviceAccountName" . }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ratelimit.fullname" . }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ratelimit.fullname" . }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "ratelimit.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "ratelimit.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
